// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYh_-jN6ApZDZpwciAuyzOpCKNSI5GrI',
    appId: '1:621319125889:web:81932f5d8e66e46bb88680',
    messagingSenderId: '621319125889',
    projectId: 'bookosphereapp',
    authDomain: 'bookosphereapp.firebaseapp.com',
    storageBucket: 'bookosphereapp.appspot.com',
    measurementId: 'G-1FPP3ZB9LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-bgT9NaDYngGM1-PA2aldXjzWpqwSSQ',
    appId: '1:621319125889:android:14d9b6a295834a18b88680',
    messagingSenderId: '621319125889',
    projectId: 'bookosphereapp',
    storageBucket: 'bookosphereapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwrlddpyJlp5JXluDQhXQ2_e5YgC6d8Q',
    appId: '1:621319125889:ios:7d37c0dd22bec768b88680',
    messagingSenderId: '621319125889',
    projectId: 'bookosphereapp',
    storageBucket: 'bookosphereapp.appspot.com',
    iosBundleId: 'com.ameypandit.bookosphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwrlddpyJlp5JXluDQhXQ2_e5YgC6d8Q',
    appId: '1:621319125889:ios:5cddcc21b067717db88680',
    messagingSenderId: '621319125889',
    projectId: 'bookosphereapp',
    storageBucket: 'bookosphereapp.appspot.com',
    iosBundleId: 'com.example.bookosphere.RunnerTests',
  );
}
